* hel-leader 2.0

A leader key extension for [[https://github.com/anuvyklack/hel][Hel]] that surves two purposes:
- Allows to use =Space= as leader key instead of =C-c= (Emacs native leader) in Hel
  Normal and Motion state.
- Allows entering Emacs =C-x=, =C-c=, =M-= and =C-M-= commands without modifier keys.

** Enable
#+begin_src emacs-lisp
(use-package s :ensure t)
(use-package hel-leader)
#+end_src

** Usage

- =SPC= (~hel-leader~) :: 

  Keys are translated according to the following rules:

  | Input     | Result    |
  |-----------+-----------|
  | =SPC=       | =C-c=       |
  | =SPC c=     | =C-c C-=    |
  | =SPC x=     | =C-x=       |
  | =SPC x x=   | =C-x C-=    |
  | =SPC m=     | =M-=        |
  | =SPC g=     | =C-M-=      |
  | =SPC <key>= | =C-c <key>= |

  Modifiers can be combined. After entering =C-x=, pressing =m= or =g= adds =M-= or =C-M-=
  to the next key.

- =C-w SPC= (~hel-leader-other-window~) ::
  Same as =SPC=, but the result buffer of the invoked command (if any) is
  opened in a new window. Equivalent to =C-w n SPC=.

- =Backspace= (~hel-leader-undo~) :: Undo the last entered key.

** Examples

| Input     | Result    |
|-----------+-----------|
| =SPC a=     | =C-c a=     |
| =SPC c t=   | =C-c C-t=   |
| =SPC c t t= | =C-c C-t t= |
| =SPC x f=   | =C-x f=     |
| =SPC x x f= | =C-x C-f=   |
| =SPC x m t= | =C-x M-t=   |
| =SPC m x=   | =M-x=       |
| =SPC g x=   | =C-M-x=     |

** Differences from the version 1

Originally the whole logic was copied from [[https://github.com/emacsorphanage/god-mode][God-Mode]].
